import 'dotenv/config';

export const env = {
  SHOPIFY_SHOP_DOMAIN: process.env.SHOPIFY_SHOP_DOMAIN!,
  SHOPIFY_ADMIN_ACCESS_TOKEN: process.env.SHOPIFY_ADMIN_API_SECRET_KEY!,
  SHOPIFY_API_VERSION: process.env.SHOPIFY_API_VERSION!,
  SHOPIFY_STOREFRONT_ACCESS_TOKEN: process.env.SHOPIFY_STOREFRONT_SECRET_TOKEN!,
};
