#!/bin/bash
set -e

REMOTE="root@91.99.156.30"
COOLIFY_APP_UUID="oez76hy971wowdm00udezycy"
COOLIFY_TOKEN="1|MtSOBWVy2DM838jWGaHI3mAmszc7TqoVuZCqIsHT5e365733"
COOLIFY_API="http://localhost:8000/api/v1"
PREBUILT_IMAGE="nnshop-prebuilt"
TAG=$(git rev-parse --short HEAD)
START_TIME=$(date +%s)

log() { echo "[$(date +%H:%M:%S)] $1"; }

log "Deploy commit: ${TAG}"

# ── 1. Pull production env ──────────────────────────────
log "Pulling production env..."
CONTAINER=$(ssh ${REMOTE} "docker ps --filter 'label=coolify.name=${COOLIFY_APP_UUID}' --format '{{.Names}}' | head -1")
if [ -n "$CONTAINER" ]; then
  ssh ${REMOTE} "docker inspect ${CONTAINER} --format '{{range .Config.Env}}{{println .}}{{end}}'" \
    | grep -v '^PATH=\|^NODE_VERSION=\|^YARN_VERSION=\|^HOSTNAME=' \
    | sort > .env.server
  log "  $(wc -l < .env.server | tr -d ' ') vars from ${CONTAINER}"
else
  log "  No running container, using existing .env.server"
fi

# ── 2. Build Next.js ────────────────────────────────────
log "Building Next.js..."
cp .env.server .env.local
npm run build 2>&1 | tail -3
rm .env.local
log "  Build done"

# ── 3. Package Docker image ─────────────────────────────
log "Packaging Docker image..."
docker build --platform linux/amd64 -f Dockerfile.deploy -t ${PREBUILT_IMAGE}:${TAG} . 2>&1 | tail -3
log "  Image built"

# ── 4. Send to server ──────────────────────────────────
log "Sending image to server..."
docker save ${PREBUILT_IMAGE}:${TAG} | gzip | ssh ${REMOTE} "gunzip | docker load"
log "  Image loaded on server"

# ── 5. Update Dockerfile to use prebuilt image ─────────
log "Updating Dockerfile..."
cat > Dockerfile << EOF
# Auto-generated by deploy.sh — uses pre-built image
FROM ${PREBUILT_IMAGE}:${TAG}
EOF

# ── 6. Commit + push → Coolify auto-deploys ────────────
log "Pushing to git..."
git add Dockerfile
git commit -m "deploy: use prebuilt image ${TAG}

Co-Authored-By: Claude Opus 4.6 (1M context) <noreply@anthropic.com>"
git push origin main
log "  Pushed"

# ── 7. Wait for Coolify deploy ─────────────────────────
log "Waiting for Coolify deploy..."
for i in $(seq 1 12); do
  sleep 5
  STATUS=$(curl -s -o /dev/null -w '%{http_code}' https://www.miomio.com.ua/api/health 2>/dev/null || echo '000')
  NEW_CONTAINER=$(ssh ${REMOTE} "docker ps --filter 'label=coolify.name=${COOLIFY_APP_UUID}' --format '{{.Image}} {{.Status}}' | head -1" 2>/dev/null)
  if [ "$STATUS" = "200" ] && echo "$NEW_CONTAINER" | grep -q "Up"; then
    END_TIME=$(date +%s)
    DURATION=$(( END_TIME - START_TIME ))
    log "Live! https://www.miomio.com.ua"
    log "  Container: ${NEW_CONTAINER}"
    log "  Total deploy time: $(( DURATION / 60 ))m $(( DURATION % 60 ))s"
    exit 0
  fi
  log "  ...waiting (http=${STATUS}, container=${NEW_CONTAINER})"
done

END_TIME=$(date +%s)
DURATION=$(( END_TIME - START_TIME ))
log "Deploy may still be in progress (${DURATION}s). Check Coolify UI."
