#!/bin/bash
set -e

REMOTE="root@91.99.156.30"
COOLIFY_APP_UUID="oez76hy971wowdm00udezycy"
COOLIFY_TOKEN="1|MtSOBWVy2DM838jWGaHI3mAmszc7TqoVuZCqIsHT5e365733"
COOLIFY_API="http://localhost:8000/api/v1"
PREBUILT_IMAGE="nnshop-prebuilt"
REGISTRY="localhost:5000"
CF_ZONE_ID="91b7648191466d72869fc9ae7f87cc0e"
CF_API_TOKEN="cfat_4w5a7UhcGNvd4wjwEpiAseeegWtTvHtUSNorugu4f2cdba93"
TAG=$(git rev-parse --short HEAD)
START_TIME=$(date +%s)

log() { echo "[$(date +%H:%M:%S)] $1"; }

log "Deploy commit: ${TAG}"

# ── 1. Pull production env ──────────────────────────────
log "Pulling production env..."
CONTAINER=$(ssh ${REMOTE} "docker ps --filter 'label=coolify.name=${COOLIFY_APP_UUID}' --format '{{.Names}}' | head -1")
if [ -n "$CONTAINER" ]; then
  ssh ${REMOTE} "docker inspect ${CONTAINER} --format '{{range .Config.Env}}{{println .}}{{end}}'" \
    | grep -v '^PATH=\|^NODE_VERSION=\|^YARN_VERSION=\|^HOSTNAME=' \
    | sort > .env.server
  log "  $(wc -l < .env.server | tr -d ' ') vars from ${CONTAINER}"
else
  log "  No running container, using existing .env.server"
fi

# ── 2. Build Next.js ────────────────────────────────────
log "Building Next.js..."
cp .env.server .env.local
npm run build 2>&1 | tail -3
rm .env.local
log "  Build done"

# ── 3. Package Docker image ─────────────────────────────
log "Packaging Docker image..."
docker build --platform linux/amd64 -f Dockerfile.deploy -t ${PREBUILT_IMAGE}:${TAG} . 2>&1 | tail -3
log "  Image built"

# ── 4. Push to server registry via SSH tunnel ───────────
log "Pushing image to server registry..."

# Open SSH tunnel: local:5000 → server:5000 (registry)
ssh -f -N -L 5000:127.0.0.1:5000 ${REMOTE} -o ExitOnForwardFailure=yes 2>/dev/null || true
TUNNEL_PID=$(lsof -ti tcp:5000 -s tcp:established 2>/dev/null | head -1)

# Tag and push through tunnel (only changed layers are sent)
docker tag ${PREBUILT_IMAGE}:${TAG} ${REGISTRY}/nnshop:${TAG}
docker push ${REGISTRY}/nnshop:${TAG}
log "  Image pushed (layer-based — only diffs sent)"

# Close SSH tunnel
if [ -n "$TUNNEL_PID" ]; then
  kill $TUNNEL_PID 2>/dev/null || true
fi

# Pull from registry and tag for Coolify
ssh ${REMOTE} "docker pull localhost:5000/nnshop:${TAG} && docker tag localhost:5000/nnshop:${TAG} ${PREBUILT_IMAGE}:${TAG}"
log "  Image tagged on server"

# ── 5. Update Dockerfile to use prebuilt image ──────────
log "Updating Dockerfile..."
cat > Dockerfile << EOF
# Auto-generated by deploy.sh — uses pre-built image
FROM ${PREBUILT_IMAGE}:${TAG}
EOF

# ── 6. Commit + push → Coolify auto-deploys ────────────
log "Pushing to git..."
git add Dockerfile
git commit -m "deploy: use prebuilt image ${TAG}

Co-Authored-By: Claude Opus 4.6 (1M context) <noreply@anthropic.com>"
git push origin main
log "  Pushed"

# ── 7. Wait for Coolify deploy ─────────────────────────
log "Waiting for Coolify deploy..."
for i in $(seq 1 12); do
  sleep 5
  STATUS=$(curl -s -o /dev/null -w '%{http_code}' https://www.miomio.com.ua/api/health 2>/dev/null || echo '000')
  NEW_CONTAINER=$(ssh ${REMOTE} "docker ps --filter 'label=coolify.name=${COOLIFY_APP_UUID}' --format '{{.Image}} {{.Status}}' | head -1" 2>/dev/null)
  if [ "$STATUS" = "200" ] && echo "$NEW_CONTAINER" | grep -q "Up"; then
    END_TIME=$(date +%s)
    DURATION=$(( END_TIME - START_TIME ))
    log "Live! https://www.miomio.com.ua"
    log "  Container: ${NEW_CONTAINER}"
    # ── 8. Purge Cloudflare cache ─────────────────────────
    log "Purging Cloudflare cache..."
    CF_RESPONSE=$(curl -s -X POST "https://api.cloudflare.com/client/v4/zones/${CF_ZONE_ID}/purge_cache" \
      -H "Authorization: Bearer ${CF_API_TOKEN}" \
      -H "Content-Type: application/json" \
      --data '{"purge_everything":true}')
    if echo "$CF_RESPONSE" | grep -q '"success":true'; then
      log "  Cloudflare cache purged"
    else
      log "  ⚠️ Cloudflare purge failed: ${CF_RESPONSE}"
    fi
    log "  Total deploy time: $(( DURATION / 60 ))m $(( DURATION % 60 ))s"
    exit 0
  fi
  log "  ...waiting (http=${STATUS}, container=${NEW_CONTAINER})"
done

END_TIME=$(date +%s)
DURATION=$(( END_TIME - START_TIME ))
log "Deploy may still be in progress (${DURATION}s). Check Coolify UI."
