#!/bin/bash
set -e

# Load secrets from .env.deploy if present
[ -f .env.deploy ] && set -a && source .env.deploy && set +a

REMOTE="${DEPLOY_REMOTE:-root@91.99.156.30}"
COOLIFY_APP_UUID="${COOLIFY_APP_UUID:-oez76hy971wowdm00udezycy}"
COOLIFY_TOKEN="${COOLIFY_TOKEN:?Set COOLIFY_TOKEN env var}"
COOLIFY_API="${COOLIFY_API:-http://localhost:8000/api/v1}"
PREBUILT_IMAGE="nnshop-prebuilt"
CF_ZONE_ID="${CF_ZONE_ID:?Set CF_ZONE_ID env var}"
CF_API_TOKEN="${CF_API_TOKEN:?Set CF_API_TOKEN env var}"
TAG=$(git rev-parse --short HEAD)
START_TIME=$(date +%s)

log() { echo "[$(date +%H:%M:%S)] $1"; }

log "Deploy commit: ${TAG}"

# ── 1. Pull production env ──────────────────────────────
log "Pulling production env..."
CONTAINER=$(ssh ${REMOTE} "docker ps --filter 'label=coolify.name=${COOLIFY_APP_UUID}' --format '{{.Names}}' | head -1")
if [ -n "$CONTAINER" ]; then
  ssh ${REMOTE} "docker inspect ${CONTAINER} --format '{{range .Config.Env}}{{println .}}{{end}}'" \
    | grep -v '^PATH=\|^NODE_VERSION=\|^YARN_VERSION=\|^HOSTNAME=' \
    | sort > .env.server
  log "  $(wc -l < .env.server | tr -d ' ') vars from ${CONTAINER}"
else
  log "  No running container, using existing .env.server"
fi

# ── 2. Build Next.js ────────────────────────────────────
log "Building Next.js..."
cp .env.server .env.local
npm run build 2>&1 | tail -3
rm .env.local
log "  Build done"

# ── 3. Sync build to server + build image remotely ──────
# rsync sends only changed bytes — first deploy ~5.8GB, subsequent ones just deltas (~seconds)
REMOTE_BUILD="/tmp/nnshop-deploy"

log "Syncing build output to server (rsync delta)..."
ssh ${REMOTE} "mkdir -p ${REMOTE_BUILD}/{.next/standalone,.next/static,public,keys}"

rsync -az --delete --progress \
  .next/standalone/ ${REMOTE}:${REMOTE_BUILD}/.next/standalone/
rsync -az --delete \
  .next/static/ ${REMOTE}:${REMOTE_BUILD}/.next/static/
rsync -az --delete \
  public/ ${REMOTE}:${REMOTE_BUILD}/public/
rsync -az --delete \
  keys/ ${REMOTE}:${REMOTE_BUILD}/keys/
scp -q Dockerfile.deploy ${REMOTE}:${REMOTE_BUILD}/Dockerfile.deploy
log "  Sync done"

log "Building Docker image on server..."
ssh ${REMOTE} "cd ${REMOTE_BUILD} && docker build -f Dockerfile.deploy -t ${PREBUILT_IMAGE}:${TAG} ."
log "  Image built on server"

# ── 4. Update Dockerfile to use prebuilt image ──────────
log "Updating Dockerfile..."
cat > Dockerfile << EOF
# Auto-generated by deploy.sh — uses pre-built image
FROM ${PREBUILT_IMAGE}:${TAG}
EOF

# ── 5. Commit + push → Coolify auto-deploys ────────────
log "Pushing to git..."
git add Dockerfile
git commit -m "deploy: use prebuilt image ${TAG}

Co-Authored-By: Claude Opus 4.6 (1M context) <noreply@anthropic.com>"
git push origin main
log "  Pushed"

# ── 6. Wait for Coolify deploy ─────────────────────────
log "Waiting for Coolify deploy..."
for i in $(seq 1 12); do
  sleep 5
  STATUS=$(curl -s -o /dev/null -w '%{http_code}' https://www.miomio.com.ua/api/health 2>/dev/null || echo '000')
  NEW_CONTAINER=$(ssh ${REMOTE} "docker ps --filter 'label=coolify.name=${COOLIFY_APP_UUID}' --format '{{.Image}} {{.Status}}' | head -1" 2>/dev/null)
  if [ "$STATUS" = "200" ] && echo "$NEW_CONTAINER" | grep -q "Up"; then
    END_TIME=$(date +%s)
    DURATION=$(( END_TIME - START_TIME ))
    log "Live! https://www.miomio.com.ua"
    log "  Container: ${NEW_CONTAINER}"
    # ── 7. Purge Cloudflare cache ─────────────────────────
    log "Purging Cloudflare cache..."
    CF_RESPONSE=$(curl -s -X POST "https://api.cloudflare.com/client/v4/zones/${CF_ZONE_ID}/purge_cache" \
      -H "Authorization: Bearer ${CF_API_TOKEN}" \
      -H "Content-Type: application/json" \
      --data '{"purge_everything":true}')
    if echo "$CF_RESPONSE" | grep -q '"success":true'; then
      log "  Cloudflare cache purged"
    else
      log "  ⚠️ Cloudflare purge failed: ${CF_RESPONSE}"
    fi
    log "  Total deploy time: $(( DURATION / 60 ))m $(( DURATION % 60 ))s"
    exit 0
  fi
  log "  ...waiting (http=${STATUS}, container=${NEW_CONTAINER})"
done

END_TIME=$(date +%s)
DURATION=$(( END_TIME - START_TIME ))
log "Deploy may still be in progress (${DURATION}s). Check Coolify UI."
