FROM node:24.13.0-slim

RUN apt-get update -y && apt-get install -y openssl curl && rm -rf /var/lib/apt/lists/*

WORKDIR /app

ENV NODE_ENV=production
ENV PORT=3000
ENV HOSTNAME="0.0.0.0"
ENV NEXT_TELEMETRY_DISABLED=1

COPY public ./public
COPY .next/standalone ./
COPY .next/static ./.next/static
COPY keys ./keys
RUN rm -f .env .env.local .env.production .env.server && \
    mkdir -p .next/cache && \
    chown -R node:node .next/cache

USER node
EXPOSE 3000
CMD ["node", "server.js"]
