export const heroSlideButton = {
  title: 'Hero Slide Button',
  name: 'heroSlideButton',
  type: 'object',
  fields: [
    {
      title: 'Label',
      name: 'label',
      type: 'string',
      validation: (Rule: any) => Rule.required(),
    },
    {
      title: 'Link URL',
      name: 'url',
      type: 'url',
      description: 'External or internal URL (e.g. /woman/new-arrivals)',
    },
    {
      name: 'collection',
      title: 'Collection',
      type: 'reference',
      description: 'Link to a collection page (used if URL is not set)',
      to: [{ type: 'collection' }],
    },
    {
      title: 'Style',
      name: 'variant',
      type: 'string',
      options: {
        list: [
          { title: 'Primary (filled)', value: 'default' },
          { title: 'Secondary (light)', value: 'secondary' },
          { title: 'Outline', value: 'outline' },
          { title: 'Ghost', value: 'ghost' },
        ],
        layout: 'radio',
      },
      initialValue: 'secondary',
    },
  ],
  preview: {
    select: { title: 'label', subtitle: 'variant' },
  },
};

export const heroSlide = {
  title: 'Hero Slide',
  name: 'heroSlide',
  type: 'object',
  groups: [
    { name: 'content', title: 'Content' },
    { name: 'media', title: 'Media' },
    { name: 'style', title: 'Style' },
    { name: 'link', title: 'Link' },
  ],
  fields: [
    {
      title: 'Title',
      name: 'title',
      type: 'string',
      group: 'content',
    },
    {
      title: 'Description',
      name: 'description',
      type: 'text',
      rows: 3,
      group: 'content',
    },
    {
      title: 'Title Color',
      name: 'titleColor',
      type: 'color',
      group: 'style',
      options: { disableAlpha: true },
    },
    {
      title: 'Description Color',
      name: 'descriptionColor',
      type: 'color',
      group: 'style',
      options: { disableAlpha: true },
    },
    {
      title: 'Text Position',
      name: 'textPosition',
      type: 'string',
      group: 'style',
      initialValue: 'bottom-left',
      options: {
        list: [
          { title: '↖ Top Left', value: 'top-left' },
          { title: '↑ Top Center', value: 'top-center' },
          { title: '↗ Top Right', value: 'top-right' },
          { title: '← Middle Left', value: 'middle-left' },
          { title: '· Middle Center', value: 'middle-center' },
          { title: '→ Middle Right', value: 'middle-right' },
          { title: '↙ Bottom Left', value: 'bottom-left' },
          { title: '↓ Bottom Center', value: 'bottom-center' },
          { title: '↘ Bottom Right', value: 'bottom-right' },
        ],
        layout: 'radio',
      },
    },
    {
      title: 'Text Background',
      name: 'textBackground',
      type: 'object',
      group: 'style',
      description: 'Semi-transparent background behind the text block',
      fields: [
        {
          title: 'Color',
          name: 'color',
          type: 'color',
          options: { disableAlpha: true },
        },
        {
          title: 'Opacity (%)',
          name: 'opacity',
          type: 'number',
          initialValue: 40,
          validation: (Rule: any) => Rule.min(0).max(100),
          options: { slider: true },
        },
        {
          title: 'Padding',
          name: 'padding',
          type: 'string',
          initialValue: 'md',
          options: {
            list: [
              { title: 'Small', value: 'sm' },
              { title: 'Medium', value: 'md' },
              { title: 'Large', value: 'lg' },
            ],
            layout: 'radio',
          },
        },
        {
          title: 'Rounded corners',
          name: 'rounded',
          type: 'boolean',
          initialValue: false,
        },
      ],
    },
    {
      title: 'Image Overlay',
      name: 'overlay',
      type: 'object',
      group: 'style',
      fields: [
        {
          title: 'Color',
          name: 'color',
          type: 'color',
          options: { disableAlpha: true },
        },
        {
          title: 'Opacity (%)',
          name: 'opacity',
          type: 'number',
          initialValue: 20,
          validation: (Rule: any) => Rule.min(0).max(100),
          options: { slider: true },
        },
      ],
    },
    {
      title: 'Image (Desktop)',
      name: 'image',
      type: 'image',
      group: 'media',
      options: { hotspot: true },
    },
    {
      title: 'Image (Mobile)',
      name: 'mobileImage',
      type: 'image',
      description: 'Optional. If set, shown on mobile instead of the desktop image.',
      group: 'media',
      options: { hotspot: true },
    },
    {
      title: 'Buttons',
      name: 'buttons',
      type: 'array',
      description: 'Up to 2 call-to-action buttons',
      group: 'link',
      of: [{ type: 'heroSlideButton' }],
      validation: (Rule: any) => Rule.max(2),
    },
    {
      title: 'Link (slide-level)',
      name: 'link',
      type: 'linkExternal',
      description: 'Makes the entire slide clickable (used when no buttons are set)',
      group: 'link',
    },
    {
      name: 'collection',
      title: 'Collection (slide-level)',
      type: 'reference',
      description: 'Makes the entire slide link to a collection (used when no buttons/link are set)',
      group: 'link',
      to: [{ type: 'collection' }],
    },
  ],
  preview: {
    select: { title: 'title', subtitle: 'textPosition', media: 'image' },
    prepare({ title, subtitle, media }: any) {
      return { title: title || 'Slide', subtitle: subtitle || 'bottom-left', media };
    },
  },
};

export const heroSlider = {
  title: 'Hero Slider',
  name: 'heroSlider',
  type: 'object',
  groups: [
    { name: 'slides', title: 'Slides', default: true },
    { name: 'video', title: 'Video' },
  ],
  fields: [
    {
      title: 'Title',
      name: 'title',
      type: 'string',
      group: 'slides',
    },
    {
      title: 'Compact Mode',
      name: 'compact',
      type: 'boolean',
      description: 'If set, the banner will have a smaller height.',
      initialValue: false,
      group: 'slides',
    },
    {
      title: 'Description',
      name: 'description',
      type: 'text',
      group: 'slides',
    },
    {
      name: 'slides',
      title: 'Slides',
      type: 'array',
      group: 'slides',
      of: [{ type: 'heroSlide' }],
    },
    {
      title: 'Video File',
      name: 'videoFile',
      type: 'file',
      group: 'video',
      description: 'Upload an MP4 video. If set, replaces the image slider entirely.',
      options: { accept: 'video/mp4,video/webm,video/*' },
    },
    {
      title: 'Video URL',
      name: 'videoUrl',
      type: 'url',
      group: 'video',
      description: 'Direct MP4/WebM URL (used if no file uploaded above)',
    },
    {
      title: 'Video Title',
      name: 'videoTitle',
      type: 'string',
      group: 'video',
    },
    {
      title: 'Video Description',
      name: 'videoDescription',
      type: 'text',
      rows: 3,
      group: 'video',
    },
    {
      title: 'Video Title Color',
      name: 'videoTitleColor',
      type: 'color',
      group: 'video',
      options: { disableAlpha: true },
    },
    {
      title: 'Video Description Color',
      name: 'videoDescriptionColor',
      type: 'color',
      group: 'video',
      options: { disableAlpha: true },
    },
    {
      title: 'Video Text Position',
      name: 'videoTextPosition',
      type: 'string',
      group: 'video',
      initialValue: 'bottom-left',
      options: {
        list: [
          { title: '↖ Top Left', value: 'top-left' },
          { title: '↑ Top Center', value: 'top-center' },
          { title: '↗ Top Right', value: 'top-right' },
          { title: '← Middle Left', value: 'middle-left' },
          { title: '· Middle Center', value: 'middle-center' },
          { title: '→ Middle Right', value: 'middle-right' },
          { title: '↙ Bottom Left', value: 'bottom-left' },
          { title: '↓ Bottom Center', value: 'bottom-center' },
          { title: '↘ Bottom Right', value: 'bottom-right' },
        ],
        layout: 'radio',
      },
    },
    {
      title: 'Video Link URL',
      name: 'videoLinkUrl',
      type: 'url',
      group: 'video',
      description: 'Makes the video clickable (external or internal URL)',
    },
    {
      title: 'Video Collection',
      name: 'videoCollection',
      type: 'reference',
      group: 'video',
      description: 'Link to a collection (used if URL is not set)',
      to: [{ type: 'collection' }],
    },
    {
      title: 'Video Overlay',
      name: 'videoOverlay',
      type: 'object',
      group: 'video',
      fields: [
        {
          title: 'Color',
          name: 'color',
          type: 'color',
          options: { disableAlpha: true },
        },
        {
          title: 'Opacity (%)',
          name: 'opacity',
          type: 'number',
          initialValue: 20,
          validation: (Rule: any) => Rule.min(0).max(100),
          options: { slider: true },
        },
      ],
    },
  ],
  // preview: {
  //   select: {
  //     title: 'title',
  //   },
  //   prepare({ title }) {
  //     return {
  //       title: title,
  //       subtitle: 'Slides',
  //     };
  //   },
  // },
};
